
output: 2236_Root_Eqauls_Sum_of_Children.o
	gcc 2236_Root_Eqauls_Sum_of_Children.o -o test

main.o: 2236_Root_Eqauls_Sum_of_Children.c
	gcc -c 2236_Root_Eqauls_Sum_of_Children.c

clean:
	@del *.o test.exe